cards/CNS-infection.md

add category

---

.eslintrc.yml
.gitignore
.travis.yml
README.md
app/cards/Card.jsx
app/cards/__tests__/Card-test.jsx
app/index.jsx
package.json
yarn.lock

Add initial test setup

---

cards/nih-stroke-scale/card.md

added a TIP for testing motor strength and a few other techniques for each scoring section. Thought it would help if a provider uses this as their sole resource to learn or in patient care

NIH stroke scale

---

cards/abg-interpretation/card.md

added a pneumonic for Non Anion gap acidosis

abg-interpretation

---

cards/delayed-sequence-intubation/card.md

updated the term NIV to NIPPV to correlate with the latest article (which I put in references)

delayed-sequence-intubation

---

cards/angioedema/card.md

here are updates for the angioedema card. mostly based on a recent EP monthly article and from that articles references

angioedema

---

cards/ecg-right-posterior-leads/card.md

ecg right sided leads

---

cards/shoulder-exam/card.md

shoulder-exam

---

cards/pediatric-weight-based-resus/card.md

pediatric-weight-based-resus

---

.gitignore
.stylintrc
app/assets/css/cards.styl
app/assets/css/contact.styl
app/assets/css/hamburger.styl
app/assets/css/header.styl
app/assets/css/lists.styl
app/assets/css/main.styl
app/assets/css/print.styl
app/assets/css/search.styl
app/assets/css/spinner.styl
app/assets/css/tables.styl
app/assets/css/typography.styl
app/assets/css/variables.styl
app/pages/Home.tsx
package.json
yarn.lock

Accelerate stylint warnings + fix broken configs

---

app/assets/css/cards.styl
cards/abdominal-pain-diagnostics/card.md
cards/against-medical-advice/card.md
cards/anaphylaxis/card.md
cards/angioedema/card.md
cards/ankle-fxs-lauge-hansen/card.md
cards/aorta-ultrasound/card.md
cards/appendicitis-acep/card.md
cards/atls/card.md
cards/atrial-fibrillation/card.md
cards/benzo-metabolism/card.md
cards/ecg-right-posterior-leads/card.md
cards/knee-injuries-knee-dislocation/card.md
cards/knee-injuries-patella-dislocation/card.md
cards/knee-injuries-patella-fracture/card.md
cards/knee-injuries/card.md
cards/pediatric-weight-based-resus/card.md
cards/shoulder-exam/card.md
gulpfile.ts

Various fixes. Reference updates.

Misc fixes 1

---

README.md
app/App.tsx
app/assets/css/announcements.styl
app/assets/css/footer.styl
app/assets/css/main.styl
app/assets/css/variables.styl
app/components/Announcements.tsx
app/components/Header.tsx
app/pages/Home.tsx
app/pages/__tests__/__snapshots__/Home-test.tsx.snap
cards/emergency-drug-card-peds/card.md
cards/tpa-code-dose/card.md

** WIP **
A few changes. Notably:
- added an announcement bar on the front page for, well, announcements
- went back to two columns on Home page, didn't want announcement bar hiding Updates
- put ALiEM footer color on ALiEM Cards footer
- added top-level link to ALiEM

Last minute hotfixes

---

app/assets/css/announcements.styl
app/assets/css/footer.styl
app/assets/css/search.styl
app/assets/css/variables.styl
app/components/Footer.tsx
app/components/Header.tsx
app/components/Search.tsx
app/components/__tests__/__snapshots__/Footer-test.tsx.snap
app/components/__tests__/__snapshots__/Search-test.tsx.snap

small style suggestions

---

app/assets/css/announcements.styl
app/components/Announcements.tsx

style change

---

cards/acetaminophen-toxicity/card.md
cards/acute-limb-ischemia/card.md
cards/against-medical-advice/card.md
cards/anaphylaxis/card.md
cards/angioedema/card.md
cards/ankle-fxs-lauge-hansen/card.md
cards/aorta-ultrasound/card.md

First real attempt at copyedit changes using VS Code! Cross-fingers (and toes). Feedback welcome - no detail too small. Wanna make sure I do this right. Thx for the walkthrough, @jvoros !

Copyedits 7 cards

---

gulpfile.ts

Build sitemap for Google Search console. Available at http://www.aliemcards.com/sitemap.txt

Build a sitemap

---

app/App.tsx
app/cards/Card.tsx
app/cards/__tests__/__snapshots__/Card-test.tsx.snap
package.json
yarn.lock

cc: @jvoros
Tested this on Google's structured data test tool and it seemed to work.

Add structured data for SEO

---

app/pages/About.tsx
app/pages/__tests__/__snapshots__/About-test.tsx.snap
cards/pain-management/card.md

Paincardfix

---

package.json

fix(package): update graphql to version 0.11.7

---

package.json

Reverts aliemteam/aliemcards#245

Revert "chore(package): update enzyme to version 3.1.0"

---

package-lock.json
package.json

React-apollo-2.0 is breaking changes...not included...

Some updates

---

app/App.tsx
app/assets/css/footer.styl
app/assets/css/main.styl
app/components/Footer.tsx
app/components/__tests__/__snapshots__/Footer-test.tsx.snap

Fix the footer problem on Mobile Safari. Better CSS anyway...

Footer fix

---

cards/eye-ddx/card.md
cards/eye-painful/card.md

Painful eye edit

---

cards/preeclampsia/card.md
package-lock.json
package.json

add preeclampsia card

---

cards/preeclampsia/card.md

edits to preeclampsia card

---

cards/tumor-lysis-syndrome/card.md

Tumor Lysis Syndrome
